apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod_eshoponweb
  name: pod_eshoponweb
spec:
  containers:
  - image: mcr.microsoft.com/azure-sql-edge:latest
    name: sqlserver
    env:
      - name: SA_PASSWORD
        value: "@someThingComplicated1234"
      - name: ACCEPT_EULA
        value: Y
    ports:
      - containerPort: 1433
        hostPort: 1433
        protocol: tcp
  - image: localhost/eshopwebmvc:latest
    name: eshopwebmvc
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep 2 && dotnet Web.dll" ]
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Podman
      - name: ASPNETCORE_URLS
        value: http://+:80
    volumeMounts:
      - mountPath: /root/.aspnet/https
        name: home-geovani-.aspnet-https-host-0
        readOnly: true
      - mountPath: /root/.microsoft/usersecrets
        name: home-geovani-.microsoft-usersecrets-host-1
        readOnly: true
    ports:
      - containerPort: 80
        hostPort: 5106
        protocol: tcp
  - image: localhost/eshoppublicapi:latest
    name: eshoppublicapi
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep 2 && dotnet PublicApi.dll" ]
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Podman
      - name: ASPNETCORE_URLS
        value: http://+:81
    volumeMounts:
      - mountPath: /root/.aspnet/https
        name: home-geovani-.aspnet-https-host-0
        readOnly: true
      - mountPath: /root/.microsoft/usersecrets
        name: home-geovani-.microsoft-usersecrets-host-1
        readOnly: true
    ports:
      - containerPort: 81
        hostPort: 5200
        protocol: tcp
  restartPolicy: Never
  volumes:
    - hostPath:
        path: /home/geovani/.aspnet/https
        type: Directory
      name: home-geovani-.aspnet-https-host-0
    - hostPath:
        path: /home/geovani/.microsoft/usersecrets
        type: Directory
      name: home-geovani-.microsoft-usersecrets-host-1
status: {}
