FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG feed_name
ARG feed_user
ARG feed_password
WORKDIR /src

RUN dotnet nuget add source https://pkgs.dev.azure.com/virtualgroup/Plataforma/_packaging/skail-dev/nuget/v3/index.json --name $feed_name --username $feed_user --password $feed_password --store-password-in-clear-text

COPY ./ ./

RUN dotnet publish ./SendEmail.csproj \
        -p:PublishSingleFile=true \
        -p:PublishReadyToRun=true \
        -r ubuntu.20.04-x64 \
        -c Release \
        --self-contained true \
        -o /skail/ 
  
FROM scratch as runtime
WORKDIR /
COPY --from=build /skail/SendEmail ./app/skail_func
COPY --from=build /skail/env.sh ./.env.sh



